BulkyBookweb/Areas/Admin/Controllers/CovertypeController.cs
using BulkyBookweb.Models;
using BulkyBookweb.Models.utility;
using BulkyBookweb.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookweb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CovertypeController : Controller
    {
        private readonly IUnitOfWork _unit;
        public CovertypeController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> CoverList = _unit.CoverType.GetAll();
            return View(CoverList);
        }
        //get
        public IActionResult Create()
        {
            return View();
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (obj.Name == obj.Id.ToString()) 
            {
                ModelState.AddModelError("name", "the display order can not exactly match the name.");
            }
            if (ModelState.IsValid)
            {
                _unit.CoverType.Add(obj);
                _unit.Save();

                return RedirectToAction("Index");
            }
            return View(obj);

        }
      
        public IActionResult Edit(int?id) {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var GetId = _unit.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (GetId== null)
            {
                return NotFound();
            }
          
           
            return View(GetId);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (obj.Name == obj.Id.ToString())
            {
                ModelState.AddModelError("name", "the display order can not exactly match the name.");
            }

            if (ModelState.IsValid)
            {
                _unit.CoverType.Update(obj);
                _unit.Save();
                TempData["success"] = "Category edited successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);

        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverDelete = _unit.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (CoverDelete == null)
            {
                return NotFound();
            }
            _unit.CoverType.Remove(CoverDelete);
            _unit.Save();
            TempData["success"] = "Category deleted successfuly";
            return RedirectToAction("Index");
        }



    }
}

BulkyBookweb/Areas/Admin/Views/Covertype/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CoverType

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-3">
            <h2 class="text-primary">create CoverType</h2>
            </hr>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
       
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Covertype" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Bact to list
        </a>
    </div>

</form>

BulkyBookweb/Areas/Admin/Views/Covertype/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CoverType

<form method="post">
    <div class="border p-3 m-4">
        <div class="row pb-3">
            <h2 class="text-primary">Edit category</h2>
            <hr>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Covertype" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Bact to list
        </a>
    </div>

</form>

BulkyBookweb/Areas/Admin/Views/Covertype/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>
<body>
    @if (TempData["success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }
    <div class"container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">Covertepe List</h2>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Covertype" asp-action="Create" class="btn btn-primary ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                    </svg> &nbsp; Create new CoverType
                </a>
            </div>

        </div>
    </div>

    <table class="table" style="width:100%">
        <thead>
            <tr>
                <th>
                    name
                </th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                    </td>
                    
                    <td width="20%">
                        <a asp-controller="Covertype" asp-action="Edit" asp-route-id="@obj.Id">Edit</a>
                        <a class="text-danger" asp-controller="Covertype" asp-action="Delete" asp-route-id="@obj.Id">DeleteCover</a>
                    </td>

                </tr>

            }
        </tbody>
    </table>

</body>
</html>