BulkyBookweb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBookweb.Models;
using BulkyBookweb.Models.utility;
using BulkyBookweb.Models.ViewModel;
using BulkyBookweb.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookweb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        
      
            private readonly IUnitOfWork _Unit;
            
            public CompanyController(IUnitOfWork Unit )
            {
                _Unit = Unit;
               

            }
            public IActionResult Index()
            {

                return View();
            }
            //get
            public IActionResult Upsert(int? id)
            {
            Company company = new Company();
               




                if (id == null || id == 0)
                {

                    return View(company);
                }
                else
                {
                    company = _Unit.Company.GetFirstOrDefault(u => u.Id == id);
                    return View(company);
                
                }



            }
            //post
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Upsert(Company obj)
            {

                if (ModelState.IsValid)
                {
                 

                    if (obj.Id == 0)
                    {
                        _Unit.Company.Add(obj);
                    TempData["success"] = "Company created successfuly";
                }
                    else
                    {
                        _Unit.Company.Update(obj);

                    TempData["success"] = "Company Updated successfuly";
                }


                    _Unit.Save();
                  
                    return RedirectToAction("Index");
                }
                return View(obj);

            }


            #region API CALLS        
            [HttpGet]
            public IActionResult GetAll()
            {
                var CompanyList = _Unit.Company.GetAll();
                return Json(new { data = CompanyList });
            }
            [HttpDelete]

            public IActionResult Delete(int? id)

            {

                var obj = _Unit.Company.GetFirstOrDefault(u => u.Id == id);
                if (obj == null)
                {
                    return Json(new { success = false, message = "Error While Deleting" });
                }
               
                _Unit.Company.Remove(obj);
                _Unit.Save();

                return Json(new { success = true, message = "Delete Successful" });
            }


            #endregion
        }
    }

BulkyBookweb/Areas/Admin/Controllers/ProductController.cs
using BulkyBookweb.Models;
using BulkyBookweb.Models.utility;
using BulkyBookweb.Models.ViewModel;
using BulkyBookweb.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookweb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _Unit;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        public ProductController(IUnitOfWork Unit, IWebHostEnvironment webHostEnvironment)
        {
            _Unit = Unit;
            _WebHostEnvironment = webHostEnvironment;

        }
        public IActionResult Index()
        {
          
            return View();
        }
        //get
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new(),
                CategoryList = _Unit.Category.GetAll().Select(
               u => new SelectListItem
               {
                   Text = u.Name,
                   Value = u.Id.ToString()
               }
               ),
                CoverTypeList = _Unit.CoverType.GetAll().Select(
             u => new SelectListItem
             {
                 Text = u.Name,
                 Value = u.Id.ToString()
             }
             ),
            };
         

           

            if (id == null || id == 0)
            {
              
                //create product
                return View(productVM);
            }
            else
            {
               productVM.Product = _Unit.Product.GetFirstOrDefault(u=>u.Id==id);
                return View(productVM);
                //update product
            }


          
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwroot = _WebHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwroot, @"Image\Products");
                    var exttension = Path.GetExtension(file.FileName);
                    if (obj.Product.ImageUrl != null)
                    {
                        var oldimagepath = Path.Combine(wwwroot, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldimagepath))
                        {
                            System.IO.File.Delete(oldimagepath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + exttension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Product.ImageUrl = @"\Image\Products\" + fileName + exttension;
                }
                    
                    if (obj.Product.Id == 0)
                   {
                        _Unit.Product.Add(obj.Product);
                    }
                   else
                   {
                        _Unit.Product.Update(obj.Product);
                   }
                
            
                _Unit.Save();
                TempData["success"] = "Product created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);

        }
    

        #region API CALLS        
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _Unit.Product.GetAll(includeproperties:"Category,CoverType");
            return Json(new { data = productList });
        }
        [HttpDelete]
      
        public IActionResult Delete (int? id)
        
        {
           
            var ProductFromDb = _Unit.Product.GetFirstOrDefault(u => u.Id == id);
            if (ProductFromDb == null)
            {
                return Json(new { success = false,message="Error While Deleting" }) ;
            }
            var oldimagepath = Path.Combine(_WebHostEnvironment.WebRootPath, ProductFromDb.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldimagepath))
            {
                System.IO.File.Delete(oldimagepath);
            }
            _Unit.Product.Remove(ProductFromDb);
            _Unit.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }


        #endregion

    }
}

BulkyBookweb/Views/Shared/_Layout.cshtml
@using BulkyBookweb.Models.utility;
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] bullky book </title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookweb.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="/Image/book.png">
    <link rel="stylesheet" href="~/css/Homepage.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand"><img src="/Image/book.png" alt="Girl in a jacket" width="30" height="30"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.IsInRole(SD.Role_Admin))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color:white;" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                           
                        
                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                        </div>
                    </li>}
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                    </li>
                    @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart) != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg> &nbsp;(@HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart))
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg> &nbsp;(0)
                            </a>
                        </li>
                    }
                   
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
  

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookweb/Views/Shared/_Notification.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
﻿@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}